INCLUDEPATH += $$PWD/src
SRC_DIR = $$PWD

BUILDDIR = $$PWD/build
DESTDIR = $$PWD/bin

OBJECTS_DIR = $$BUILDDIR
MOC_DIR = $$BUILDDIR
RCC_DIR = $$BUILDDIR
UI_DIR = $$BUILDDIR

QMAKE_LFLAGS += -Wl,-rpath,$$DESTDIR
